config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'inventory', to: 'inventory#index'
  post 'inventory/order', to: 'inventory#order'

  post 'inventory', to: 'inventory#index'
  patch 'inventory/edit', to: 'inventory#edit'
  post 'inventory/edit', to: 'inventory#edit'
  post 'inventory/destory', to: 'inventory#destroy'
  get 'events', to: 'events#index'
  post 'events', to: 'events#index'
  post 'events/edit', to: 'events#edit'
  patch 'events/edit', to: 'events#edit'
  post 'events/destroy', to: 'events#destroy'
  resources :users
  get 'users/new'

  get 'inventory', to: 'inventory#index'
  post 'inventory/create', to: 'inventory#create'
	post 'inventory/edit', to: 'inventory#edit'
	post 'inventory/destroy', to: 'inventory#destroy'
	get 'inventory/survey', to: 'inventory#survey'

  get 'about', to: 'pages#about'
  get 'help', to: 'pages#help'
  get 'resources', to: 'pages#resources'
  get 'inventory', to: 'pages#inventory'
  get 'contact', to: 'contact#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  
  get 'welcome/index'
  post 'welcome/edit'
  put 'welcome/update'

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if current_user
			@is_admin = current_user.admin
		else
			@is_admin = false
		end

    if Contact.first == nil
      @contact = Contact.create!({:email => 'fill me out!', :facebook => 'fill me out!', :location => 'fill me out!', :hours => "fill me out!"})
    else
    	@contact = Contact.first
    end
  end

  def edit
    @contact = Contact.first
  end

  def update
    @contact = Contact.first
  	@contact.update_attributes!(params.require(:contact).permit(:email, :facebook, :location, :hours))
  	flash[:notice] = "Contact information was successfully updated"
  	redirect_to root_path
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/edit.html.erb
<div class='editContactsContainer'>
	<h2>Edit Contact Page</h2>

	<%= form_tag welcome_update_path, :method => :put do %>
		<%= label :contact, :email, 'Email: ' %>
		<%= text_field :contact, 'email', :size=>"50" %>
		<br>

		<%= label :contact, :facebook, 'Facebook: ' %>
		<%= text_field :contact, 'facebook', :size=>"50" %>
		<br>

		<%= label :contact, :hours, 'Hours: ' %>
		<%= text_area :contact, 'hours', :rows=>"7" %>
		<br>

		<%= label :contact, :location, 'Location: ' %>
		<%= text_field :contact, 'location', :size=>"50" %>
		<br>

		<%= submit_tag 'Update Contact Info', class:'btn btn-primary' %>

	<% end %>
</div>

app/views/welcome/index.html.erb
<div class="splash-page">

  <div class="row">
      <div class="first-column col-xs-6">
        <h2>Location: </h2>
        <h4>Stiles Hall at 2400 Bancroft Way</h4>
        <div id="map-canvas"></div>
        <br>
      </div>
        <div class="splash-info col-xs-6">
          <h2>Hours for Spring 2015</h2>
          <ul>
            <% @contact.hours_format.each do |day| %>
                <h4><%= day%></h4>
            <%end %>
          </ul>
          <% if @is_admin %>
              <%= button_to 'Edit Contact Info', welcome_edit_path, class: "btn btn-primary edit-contact" %>
          <% end %>
        </div>
    </div>

</div>

<script>
function initialize() {
    var mapCanvas = document.getElementById('map-canvas');
    var mapOptions = {
        center: new google.maps.LatLng(37.868469, -122.261213),
        zoom: 18,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions)
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>